import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  learnSidebar: [{type: 'autogenerated', dirName: 'learn'}],
  farmingSidebar: [{type: 'autogenerated', dirName: 'farming'}],
};

export default sidebars;
